/**
 * WAPSI gateway — fabric mode adapter.
 *
 * Submits the same seven operations to the WAPSI chaincode deployed on the
 * Drunix test network (or a Hyperledger Fabric test-network fallback) via
 * @hyperledger/fabric-gateway. Connection artifacts come from ../network
 * (generated by network/setup.sh).
 *
 * Enable with:  WAPSI_MODE=fabric node server.js   (after: npm i @hyperledger/fabric-gateway)
 * Requires:     a running network with chaincode "wapsi" on channel "wapsich".
 */
"use strict";

const fs = require("fs");
const path = require("path");
// NOTE: @grpc/grpc-js and @hyperledger/fabric-gateway are required lazily
// inside getContract() so demo mode never needs them installed.

const CHANNEL = process.env.WAPSI_CHANNEL || "wapsich";
const CHAINCODE = process.env.WAPSI_CC || "wapsi";
const MSP_ID = process.env.WAPSI_MSP || "Org1MSP";
// fabric-samples style layout: peerOrganizations/<org>.example.com/...
// MSP "Org1MSP" -> org name "org1" (strip the MSP suffix)
const ORG_DOMAIN = process.env.WAPSI_ORG_DOMAIN || `${MSP_ID.replace(/MSP$/, "").toLowerCase()}.example.com`;
const ORG_USER = process.env.WAPSI_ORG_USER || `User1@${ORG_DOMAIN}`;
const NETWORK_ROOT = process.env.WAPSI_NETWORK_ROOT || [
  path.resolve(process.env.HOME || process.env.USERPROFILE || "", ".wapsi/drunix/drunix-network/test-network"),
  path.resolve(process.env.HOME || process.env.USERPROFILE || "", ".wapsi/fabric-samples/test-network"),
  path.resolve(__dirname, "../network"),
].find((p) => fs.existsSync(path.join(p, "organizations"))) || path.resolve(__dirname, "../network");
const IS_DRUNIX = NETWORK_ROOT.includes("drunix");
const ORG_PEER = process.env.WAPSI_ORG_PEER || `${IS_DRUNIX ? "peer1" : "peer0"}.${ORG_DOMAIN}`;
const CRYPTO_PATH = path.join(NETWORK_ROOT, "organizations/peerOrganizations", ORG_DOMAIN);
const KEY_DIR = path.join(CRYPTO_PATH, `users/${ORG_USER}/msp/keystore`);
const CERT_DIR = path.join(CRYPTO_PATH, `users/${ORG_USER}/msp/signcerts`);
const TLS_CERT = IS_DRUNIX
  ? path.join(CRYPTO_PATH, `peers/${ORG_PEER}/tls/tlscacerts/tls-localhost-${MSP_ID === "Org2MSP" ? "8054" : "7054"}-ca-${MSP_ID.replace(/MSP$/, "").toLowerCase()}.pem`)
  : path.join(CRYPTO_PATH, `peers/${ORG_PEER}/tls/ca.crt`);
const DEFAULT_PEER_PORT = IS_DRUNIX ? (MSP_ID === "Org2MSP" ? "9061" : "7061") : (MSP_ID === "Org2MSP" ? "8051" : "7051");
const PEER_ENDPOINT = process.env.WAPSI_PEER || `localhost:${DEFAULT_PEER_PORT}`;
const TLS_SERVER_NAME = process.env.WAPSI_TLS_SERVER_NAME || `${IS_DRUNIX ? "peer0" : ORG_PEER}.${ORG_DOMAIN}`;

let contract = null;

async function getContract() {
  if (contract) return contract;
  const grpc = require("@grpc/grpc-js");
  const crypto = require("node:crypto");
  const { connect, signers } = require("@hyperledger/fabric-gateway");

  const cred = {
    mspId: MSP_ID,
    privateKeyPem: readFirst(KEY_DIR),
    clientCertPem: readFirst(CERT_DIR),
  };
  const tlsRootCert = fs.readFileSync(TLS_CERT);
  const peer = await new grpc.Client(PEER_ENDPOINT, grpc.credentials.createSsl(tlsRootCert), {
    "grpc.ssl_target_name_override": TLS_SERVER_NAME,
  });
  contract = (await connect({
    client: peer,
    // fabric-gateway v1.x: credentials = the X.509 certificate PEM bytes directly
    identity: { mspId: cred.mspId, credentials: cred.clientCertPem },
    signer: signers.newPrivateKeySigner(crypto.createPrivateKey(cred.privateKeyPem)),
    // Timeout defaults are fine for a demo.
  })).getNetwork(CHANNEL).getContract(CHAINCODE);
  return contract;
}

function readFirst(dir) {
  const f = fs.readdirSync(dir)[0];
  return fs.readFileSync(path.join(dir, f));
}

// Map REST op names to chaincode calls.
const CC = {
  CreateCase: ["CreateCase", (b) => ({ caseId: b.caseId, complaintRef: b.complaintRef, victimBank: b.victimBank, claimedAmount: String(b.claimedAmount), reportedAt: b.reportedAt })],
  AttestHop: ["AttestHop", (b) => ({ caseId: b.caseId, hopId: b.hop.hopId, srcBank: b.hop.srcBank, srcAcctToken: b.hop.srcAcctToken, dstBank: b.hop.dstBank, dstAcctToken: b.hop.dstAcctToken, amount: String(b.hop.amount), timestamp: b.hop.timestamp, paymentRef: b.hop.paymentRef })],
  ComputeTrace: ["ComputeTrace", (b) => ({ caseId: b.caseId, rule: b.rule })],
  ComputeTraceBody: ["ComputeTrace", (b) => ({ caseId: b.caseId, rule: b.rule })],
  RecordLien: ["RecordLien", (b) => ({ caseId: b.caseId, bank: b.bank, acctToken: b.acctToken, lienAmount: String(b.lienAmount) })],
  RecordLienBody: ["RecordLien", (b) => ({ caseId: b.caseId, bank: b.bank, acctToken: b.acctToken, lienAmount: String(b.lienAmount) })],
  FlagDeadline: ["FlagDeadline", (b) => ({ caseId: b.caseId, lienId: b.lienId, asOf: b.asOf || "" })],
  FlagDeadlineBody: ["FlagDeadline", (b) => ({ caseId: b.caseId, lienId: b.lienId, asOf: b.asOf || "" })],
  ProposeRestoration: ["ProposeRestoration", (b) => ({ caseId: b.caseId, rule: b.rule || "" })],
  ProposeRestorationBody: ["ProposeRestoration", (b) => ({ caseId: b.caseId, rule: b.rule || "" })],
  ApproveAction: ["ApproveAction", (b) => ({ caseId: b.caseId, actionId: b.actionId })],
  ApproveActionBody: ["ApproveAction", (b) => ({ caseId: b.caseId, actionId: b.actionId })],
  // read-only chaincode queries (evaluate-only)
  GetCase: ["GetCase", (b) => ({ caseId: b.caseId })],
  GetTrace: ["GetTrace", (b) => ({ caseId: b.caseId })],
  GetLiens: ["GetLiens", (b) => ({ caseId: b.caseId })],
  GetProposal: ["GetProposal", (b) => ({ caseId: b.caseId, actionId: b.actionId })],
};

async function callChaincode(msp, fnName, argsObj) {
  const entry = CC[fnName];
  if (!entry) throw Object.assign(new Error(`unknown op ${fnName}`), { status: 400 });
  const [ccFn, buildArgs] = entry;
  const c = await getContract();
  const args = buildArgs(argsObj || {});
  const isRead = fnName === "ComputeTrace" || fnName === "ComputeTraceBody" || fnName.startsWith("Get");
  const call = isRead ? c.evaluateTransaction.bind(c) : c.submitTransaction.bind(c);
  const result = await call(ccFn, ...Object.values(args).map(String));
  const decoded = new TextDecoder().decode(result);
  // Chaincode reads (e.g. GetLiens with no liens yet) can return empty bytes.
  if (decoded === "") {
    if (ccFn === "GetLiens") return [];
    return null; // other reads: nothing stored yet
  }
  return JSON.parse(decoded);
}

async function submitOrEval(msp, fnName, req) {
  return callChaincode(msp, fnName, { ...(req.body || {}), ...(req.params || {}) });
}

// Read-only evaluate used by the /api/cases/:id style GET routes in fabric mode.
async function evaluate(msp, fnName, args) {
  const [first, second] = args || [];
  return callChaincode(msp, fnName, { caseId: first, actionId: second });
}

module.exports = { submitOrEval, evaluate };
